annotell/annotell-python

- annotell-input-api/annotell/input_api/input_api_client.py
Changed so that only one method for creating images inputs is public
> Slam input api client

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/input_api_model.py
solves
https://annotell.atlassian.net/browse/BE-948
> Added TimeSpecification to SLAM python model

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/input_api_client.py
Added docstrings for all public methods in the InputApiClient
> Added docstrings for all public methods

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/input_api_client.py
New method corresponding to the new route in:
https://annotell.atlassian.net/browse/BE-946
> New method: count_inputs_for_external_ids

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/input_api_client.py
Updates regarding
https://annotell.atlassian.net/browse/BE-940 and
https://annotell.atlassian.net/jira/software/projects/BE/boards/7?selectedIssue=BE-888
Before merging, remember to update version in __init__.py and README.
> Updated input_api_client

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/annoutil.py
- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/input_api_model.py
Switch to using internal ids `UUIDs` for invalidate input
Add `get_inputs` endpoint
> Be 987 1142

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/input_api_model.py
- annotell-input-api/examples/calibration.py
- annotell-input-api/examples/image.py
- annotell-input-api/examples/images.py
- annotell-input-api/examples/point_cloud.py
- annotell-input-api/examples/point_cloud_with_images.py
First stab at readme - to be deployed.
Minor convenience methods to lower the bar for creating inputs.
> Input api documentation

- docs-src/includes/_annotell_input_api.md
Changed calibration text, added example and changed structure.
> Update calibration docs

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/input_api_client.py
Re-directed get calbration path to point towards v0 route
> re-directed get-calibration path

- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/model/v1/__init__.py
- annotell-input-api/annotell/input_api/model/v1/cameras.py
- annotell-input-api/annotell/input_api/model/v1/common_models.py
- annotell-input-api/annotell/input_api/model/v1/lidars_and_cameras_sequence.py
- annotell-input-api/annotell/input_api/resources/abstract/creatable_input_api_resource.py
- annotell-input-api/annotell/input_api/resources/input/cameras.py
- annotell-input-api/annotell/input_api/resources/input/lidar_camera_sequence.py
- annotell-input-api/examples/calibration.py
- annotell-input-api/examples/cameras.py
Solves jira: https://annotell.atlassian.net/browse/INT-16
Added support for cameras input to the python client.
> Int 16 cameras support final final

- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/resources/input/cameras_sequence.py
- annotell-input-api/examples/cameras.py
- annotell-input-api/examples/cameras_seq.py
Added cameras sequence to python client
> Int 63 add python method for cameras seq

- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/model/input/lidars_and_cameras/lidars_and_cameras.py
- annotell-input-api/annotell/input_api/resources/input/lidars_and_cameras.py
- annotell-input-api/examples/lidars_and_cameras.py
Added python code including example for creating lidars_and_cameras input
> Add support for lidars_and_cameras

- annotell-input-api/annotell/input_api/model/input/abstract/__init__.py
- annotell-input-api/annotell/input_api/model/input/abstract/camera_frame.py
- annotell-input-api/annotell/input_api/model/input/abstract/camera_input.py
- annotell-input-api/annotell/input_api/model/input/abstract/sequence_frame.py
- annotell-input-api/annotell/input_api/model/input/cameras/cameras.py
- annotell-input-api/annotell/input_api/model/input/cameras/frame.py
- annotell-input-api/annotell/input_api/model/input/cameras_sequence/cameras_sequence.py
- annotell-input-api/annotell/input_api/model/input/cameras_sequence/frame.py
- annotell-input-api/annotell/input_api/model/input/lidars_and_cameras_sequence/frame.py
- annotell-input-api/annotell/input_api/model/input/lidars_and_cameras_sequence/lidars_and_cameras_sequence.py
- annotell-input-api/annotell/input_api/resources/abstract/creatable_input_api_resource.py
Solves https://annotell.atlassian.net/browse/INT-94
the code setting the camera_settings (in case it is None) did not work due to all our restructuring. Easiest way to get dataclass to work with default values was to create both a CameraFrame and a SequenceFrame class
> fixed bug in Input API client

- annotell-input-api/annotell/input_api/model/__init__.py
- annotell-input-api/annotell/input_api/model/ego/__init__.py
- annotell-input-api/annotell/input_api/model/ego/vehicle_pose.py
- annotell-input-api/annotell/input_api/model/input/lidars_and_cameras_sequence/frame.py
- annotell-input-api/annotell/input_api/resources/input/lidars_and_cameras_sequence.py
- annotell-input-api/examples/lidars_and_cameras_seq_full.py
- annotell-input-api/tests/lidars_and_cameras_seq_test.py
Companion-PR to https://github.com/annotell/annotell/pull/2236
> Add ego vehicle motion support, including tests and examples code

- annotell-input-api/annotell/input_api/model/annotation/export_annotation.py
- annotell-input-api/annotell/input_api/resources/input/input.py
- annotell-input-api/examples/invalidate_inputs.py
Solves the python part of: https://annotell.atlassian.net/browse/INT-154
> new invalidate inputs route

- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/resources/abstract/creatable_input_api_resource.py
- annotell-input-api/annotell/input_api/resources/abstract/input_api_resource.py
- annotell-input-api/annotell/input_api/resources/annotation/annotation.py
- annotell-input-api/annotell/input_api/resources/calibration/calibration.py
- annotell-input-api/annotell/input_api/resources/input/cameras.py
- annotell-input-api/annotell/input_api/resources/input/cameras_sequence.py
- annotell-input-api/annotell/input_api/resources/input/input.py
- annotell-input-api/annotell/input_api/resources/input/lidars_and_cameras.py
- annotell-input-api/annotell/input_api/resources/input/lidars_and_cameras_sequence.py
- annotell-input-api/annotell/input_api/resources/project/project.py
Allows easier subclassing for extended clients
> make _client and _file_client available

- docs-src/docs/input-api/overview.md
Added docs for metadata fields
> Update docs to include text on metadata

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/annoutil.py
- annotell-input-api/annotell/input_api/model/input/input_entry.py
python part of https://annotell.atlassian.net/browse/INT-271
Added view_link to Input model and changed annoutil to use the url in the input
> Int 271 input view links

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/model/input/input_entry.py
Adds calibration when fetching inputs
> Int 330 calibration

- docs-src/docs/input-api/annotation_types.md
- docs-src/docs/input-api/overview.md
- docs-src/docs/input-api/project.md
- docs-src/sidebars.js
Added in the docs a section about Annotation Types, about creating batches and fixed some errors
> Annotation types in docs

- annotell-input-api/annotell/input_api/model/input/input_entry.py
Adds created timestamp to input
> add created to input

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/model/calibration/calib.py
- annotell-input-api/annotell/input_api/model/calibration/sensors.py
Deserialize dictionary properly when fetching calibrations
> deserialize calibration in SensorCalibration

- .gitignore
- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/__init__.py
- annotell-input-api/annotell/input_api/resources/input/input.py
- annotell-input-api/examples/get_inputs.py
- annotell-input-api/tests/get_inputs_test.py
Solves https://annotell.atlassian.net/browse/INT-406
Thought it was strange that get_inputs method doesn't take the input_uuid since we respond with it from the create methods. I also needed this for a test I'm writing
> Added input_uuids as parameter to get_inputs method

- annotell-input-api/tests/invalidate_inputs_test.py
Solves: https://annotell.atlassian.net/browse/INT-429
> Fixed invalidate inputs test

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/input_api_client.py
- annotell-input-api/annotell/input_api/model/input/lidars/__init__.py
- annotell-input-api/annotell/input_api/model/input/lidars/frame.py
- annotell-input-api/annotell/input_api/model/input/lidars/lidars.py
- annotell-input-api/annotell/input_api/model/input/lidars_sequence/__init__.py
- annotell-input-api/annotell/input_api/model/input/lidars_sequence/frame.py
- annotell-input-api/annotell/input_api/model/input/lidars_sequence/lidars_sequence.py
- annotell-input-api/annotell/input_api/resources/input/lidars.py
- annotell-input-api/annotell/input_api/resources/input/lidars_sequence.py
- annotell-input-api/examples/lidars.py
- annotell-input-api/examples/lidars_seq.py
- annotell-input-api/tests/lidars_seq_test.py
- annotell-input-api/tests/lidars_test.py
- annotell-input-api/tests/utils.py
Adds support for:
- `lidars`
- `lidars_sequence`
> add support for lidar and lidar_seq

- annotell-input-api/README.md
- annotell-input-api/annotell/input_api/annoutil.py
- annotell-input-api/annotell/input_api/resources/input/input.py
- annotell-input-api/examples/get_inputs.py
- annotell-input-api/examples/get_inputs_by_uuids.py
- annotell-input-api/tests/annoutil_test.py
- annotell-input-api/tests/get_inputs_test.py
- annotell-input-api/tests/invalidate_inputs_test.py
Solves: https://annotell.atlassian.net/browse/INT-406
> Added method to get inputs using only uuids

- annotell-input-api/annotell/input_api/model/annotation/client_annotation.py
- annotell-input-api/annotell/input_api/resources/annotation/annotation.py
- annotell-input-api/examples/get_annotation.py
- annotell-input-api/examples/get_project_annotations.py
- annotell-input-api/tests/get_annotations_test.py
- annotell-input-api/tests/get_project_annotations_test.py
Tests are currently failing if you don't create inputs and create a client annotation yourself, added a jira to fix this: https://annotell.atlassian.net/browse/INT-663
> Altered get_annotation method and examples

- annotell-input-api/tests/create_calibrations_test.py
- annotell-input-api/tests/get_annotations_test.py
- annotell-input-api/tests/get_project_annotations_test.py
Some of our tests have been broken, since we don't have sufficient coverage for exports in the testdata. However, staging is generally not changing much and with these changes all tests pass if you run them towards staging.
> Fixed tests towards staging

- annotell-input-api/annotell/input_api/model/input/lidars_and_cameras/frame.py
Fixes circular imports bug in client
> Fixed bug with ciruclar imports

- docs-src/docs/input-api/resources/pointclouds.md
Solves: https://annotell.atlassian.net/browse/INT-924
> csv correct type

- docs-src/docs/input-api/inputs/lidars_and_cameras_seq.md
Adds documentation for shutter timings specified via Image metadata.
> Document shutter times

- annotell-input-api/README.md
- annotell-input-api/setup.py
annotell-base-clients need to be a dependency to annotell-input-api
> added dependency on annotell-base-clients and updated README

- docs-src/docs/input-api/calibration.md
Depends on example code updates from #156
Second commit is responsible for the big diff; lots of small markdown refinements.
> Int 1214 update docs for lidar fov
